---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dental-office
  namespace: staging
  labels:
    app: dental-office
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dental-office
  template:
    metadata:
      labels:
        app: dental-office
    spec:
      containers:
        - name: dental-office
          image: 294811443119.dkr.ecr.ap-southeast-2.amazonaws.com/dental-office:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 300m
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: dental-office
  namespace: staging
spec:
  selector:
    app: dental-office
  ports:
    - protocol: TCP
      port: 8080
